name: CI
on:
  pull_request:
  push:

jobs:
  test:
    runs-on: ubuntu-latest

    steps:
    - name: Install sbt
      uses: sbt/setup-sbt@v1
    - name: Checkout
      uses: actions/checkout@v5
    - name: Setup JDK
      uses: actions/setup-java@v5
      with:
        distribution: 'temurin'
        java-version: '25'
        cache: 'sbt'
    - name: Compile
      run: sbt compile
    - name: Run tests
      run: sbt -v +test
    - name: Build samples
      run: sbt "run build"
